force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Tarea</label>
    <nameField>
        <label>Nombre de Tarea</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tareas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/ActivityDate__c.field-meta.xml
<CustomField>
    <fullName>ActivityDate__c</fullName>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/LastBlockedBy__c.field-meta.xml
<CustomField>
    <fullName>LastBlockedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bloqueado por</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/LastBlockedDate__c.field-meta.xml
<CustomField>
    <fullName>LastBlockedDate__c</fullName>
    <label>Fecha de ultimo bloqueo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/List__c.field-meta.xml
<CustomField>
    <fullName>List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Tareas</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En progreso</fullName>
            </value>
            <value>
                <fullName>Terminado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaskController.cls
public with sharing class TaskController {
    @AuraEnabled        
    public static List<Task__c> getTasks (String recordId){
        return [SELECT Id, Name, ActivityDate__c, Status__c, OwnerId, Owner.Name FROM Task__c WHERE  List__c =: recordId];
    }  
    
    @AuraEnabled        
    public static Task__c getTask (String recordId){
        return [SELECT Id, Name, ActivityDate__c, Status__c, LastBlockedBy__c, LastBlockedDate__c, OwnerId, Owner.Name FROM Task__c WHERE  Id =: recordId];
    }  

    @AuraEnabled        
    public static void setSubject (String recordId, String subject){
        Task__c t = new Task__c();
        t.Id = recordId;
        t.Name = subject;
        update t;        
    } 
    
    @AuraEnabled        
    public static void toogleStatusTask (String recordId){
        Task__c t = [SELECT Id, Name, ActivityDate__c, Status__c, OwnerId, Owner.Name FROM Task__c WHERE  Id =: recordId];
        if (t.Status__c == 'En progreso'){
            t.Status__c = 'Terminado';
        }else{
            t.Status__c = 'En progreso';
        }
        update t;
    } 
}