force-app/main/default/objects/Container__c/Container__c.object-meta.xml
<CustomObject>
    <label>Notas/Listas</label>
    <nameField>
        <label>Nombre de Notas Listas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes / Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Container__c/fields/isBlocked__c.field-meta.xml
<CustomField>
    <fullName>isBlocked__c</fullName>
    <formula>NOT(ISBLANK(LastBlockedBy__c)) &amp;&amp; (((NOW() -  LastBlockedDate__c  ) * 24 * 60 * 60 ) &lt; 300 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>¿Bloqueado?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/LastBlockedBy__c.field-meta.xml
<CustomField>
    <fullName>LastBlockedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bloqueado por</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NotesLists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Container__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nota</fullName>
            </value>
            <value>
                <fullName>Lista</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ListController.cls
public with sharing class ListController {
    //Obtiene las notas y listas de la base de datos
    
    @AuraEnabled    
    public static List<Container__c> getNotesLists (){
        return [SELECT Id, Name, Type__c, Owner.Name, CreatedDate, isBlocked__c, LastBlockedBy__c,LastBlockedBy__r.Name,LastBlockedDate__c FROM Container__c ORDER BY OwnerId, CreatedDate DESC];
    }

    @AuraEnabled
    public static User getCurrentUser(){
        return [SELECT Id, Name FROM User WHERE Id =: UserInfo.getUserId()];
    }
}